In [2485]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split as tts
from sklearn.datasets import load_digits

digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [2487]:
X_train, X_test, y_train, y_test = tts(digits.data,digits.target,test_size=0.3)

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9574074074074074

In [2489]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9796296296296296

In [2491]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

In [2493]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [2497]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index) # left for training, right for test

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [2499]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [2511]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)

scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LinearRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))
    
print(f'LinearRegression scores: {scores_l}')
print(f'SVC scores: {scores_svm}')
print(f'RandomForestClassifier scores: {scores_rf}')

LinearRegression scores: [0.5210503111571501, 0.5681424219493626, 0.41943985059688327]
SVC scores: [0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
RandomForestClassifier scores: [0.9482470784641068, 0.9532554257095158, 0.9332220367278798]


In [2533]:
from sklearn.model_selection import cross_val_score

print(cross_val_score(SVC(), digits.data, digits.target, cv=3)) # this is same as upper written code
print(cross_val_score(LinearRegression(), digits.data, digits.target, cv=3))
print(cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=3))

[0.96494157 0.97996661 0.96494157]
[0.52105031 0.56814242 0.41943985]
[0.93155259 0.95659432 0.92320534]
